name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Ci test
      user : actions/checkout@v3
    - name: Set up Python 3.10
    - name: Install dependencies
      run: |
        git checkout main
        python -m pip install --upgrade pip
        pip install -r requirements.txt
